# Generated by Django 3.2.5 on 2021-10-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('Urban Gospel', 'Urban Gospel'), ('Trending', 'Trending'), ('Just In', 'Just In'), ('Contempoary', 'Contempoary'), ('Fresh Gossip', 'Fresh Gossip'), ('New Single', 'New Single'), ('Stories', 'Stories')], max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='feature_image',
            field=models.ImageField(upload_to='news-gallery/'),
        ),
    ]
