# Generated by Django 3.2.6 on 2021-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapcodes', '0002_auto_20211022_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_Image', models.ImageField(upload_to='news_gallery/')),
                ('category', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('Urban Gospel', 'Urban Gospel'), ('Trending', 'Trending'), ('Just In', 'Just In'), ('Contempoary', 'Contempoary'), ('Fresh Gossip', 'Fresh Gossip'), ('New Single', 'New Single'), ('Stories', 'Stories')], max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'WhatsNew',
            },
        ),
    ]
