# Generated by Django 3.2.6 on 2021-10-23 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strapcodes', '0003_whatsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnew',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
