# Generated by Django 3.2.6 on 2021-10-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strapcodes', '0004_whatsnew_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsnew',
            name='pub_date',
        ),
    ]
